package model;

public enum CommandType {
    FILE_REQUEST,
    FILE_DOWNLOAD,
    FILE_UPLOAD,
    LIST_REQUEST,
    LIST_SORT_AZ_REQUEST,
    LIST_SORT_FIRST_FOLDERS_REQUEST,
    LIST_SORT_AZ_RESPONSE,
    LIST_MESSAGE,
    DELETE_REQUEST,
    RENAME_REQUEST,
    RENAME_RESPONSE,
    PATH_UP,
    PATH_RESPONSE,
    PATH_IN_REQUEST,
    FOLDER_CREATE_REQUEST,
    FOLDER_CREATE_RESPONSE
}
